
import random
from math import exp

file = open('fields.gpi', 'w+')
file1 = open('matrix.txt', 'w+')

s = ""
s += '# set terminal pngcairo  transparent enhanced font "arial,10" fontscale 1.0 size 500, 350 "\n'
s += '# set output "heatmaps.2.png"\n'
s += 'unset key\n'
s += 'set view map\n'
s += 'set xtics border in scale 0,0 mirror norotate  offset character 0, 0, 0 autojustify\n'
s += 'set ytics border in scale 0,0 mirror norotate  offset character 0, 0, 0 autojustify\n'
s += 'set ztics border in scale 0,0 nomirror norotate  offset character 0, 0, 0 autojustify\n'
s += 'set nocbtics\n'
s += 'set rtics axis in scale 0,0 nomirror norotate  offset character 0, 0, 0 autojustify\n'
s += 'set title "Heat Map generated by \'plot\' from a stream of XYZ values NB: Rows must be separated by blank lines!"\n'
s += 'set xrange [ -0.500000 : 19.50000 ] noreverse nowriteback\n'
s += 'set yrange [ -0.500000 : 19.50000 ] noreverse nowriteback\n'
s += 'set cblabel "Score" \n'
s += 'set cbrange [ 0.00000 : 20.00000 ] noreverse nowriteback\n'
s += 'set palette rgbformulae -7, 2, -7\n'

s += 'set title "Heat Map generated by \'plot\' from a stream of XYZ values. NB: Rows must be separated by blank lines!"\n'

s += '\nplot "-" using 2:1:3 with image\n'

file.write(s + "\n")

for i in range(20):
	s = ''
	for j in range (20):
		rand = 20 / ((abs(i - 10)**2 + abs(j - 10)**2) + 1)**.5
		rand = round(rand)
		#s = raw_input(str(rand))
		s += str(i) + " " + str(j) + " " + str(rand) + " "
		file.write(str(i) + " " + str(j) + " " + str(rand) + "\n")
	file1.write(s + "\n")
	file.write("\n")
